### ISSUE TITLE
Allow adding new key to IC config for custom nucleus

### ISSUE THREAD

**Issue by nilssass** [smash-transport/smash-vhlle-hybrid#34]
SMASH as IC stage allows to use custom nucleus data which are loaded from a file. To do so, the IC config needs to include the keys `File_Directory` and `File_Name` which looks then like this:
```
Modi:
    Collider:
        Projectile:
            Particles: {2212: 44, 2112: 52}  # Ru
            Custom:
                File_Directory: "/path/to/nucleus_file/directory
                File_Name: "nucleus_filename.dat"
        Target:
            Particles: {2212: 44, 2112: 52}
            Custom:
                File_Directory: "/path/to/nucleus_file/directory"
                File_Name: "nucleus_filename.dat"

        Fermi_Motion: frozen
        Impact:
            Value: 5.8
```
However, the hybrid handler does not allow to add new keys. In order to run with custom nucleus files the hybrid handler should have an option to add these keys, such that one single IC base config file is enough to have.
